dependencies:
- alias: expose
  name: exposecontroller
  repository: '@chartmuseum.jenkins-x.io'
  version: 2.3.92
- alias: cleanup
  name: exposecontroller
  repository: '@chartmuseum.jenkins-x.io'
  version: 2.3.92
- alias: preview
  name: jx-spring-test
  repository: file://../jx-spring-test
  version: 0.0.0-SNAPSHOT-PR-01-3
